language: python
sudo: false
dist: trusty
services:
- docker
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/google-cloud-sdk"
_before_install: &_before_install
  - openssl aes-256-cbc -K $encrypted_fc69f8f90972_key -iv $encrypted_fc69f8f90972_iv
    -in .gcs.json.enc -out gcs.json -d || rm -f gcs.json
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
    CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - pip2 install google-compute-engine
  - if [ -f gcs.json ]; then gcloud auth activate-service-account --key-file=gcs.json; fi
_install: &_install
  - gimme 1.8
  - source ~/.gimme/envs/latest.env
  - pip install --upgrade pip
  - pip install -r requirements.txt codecov
  - pip install -e .
_coverage: &_coverage
  - SCRIPT="coverage run -m unittest discover"
matrix:
  include:
    - python: 3.4
      env: *_coverage
      before_install: *_before_install
      install: *_install
    - python: 3.5
      env: *_coverage
      before_install: *_before_install
      install: *_install
    - python: 3.6
      env: SCRIPT="pep8 --max-line-length=99 ."
      install: pip install pep8
    - python: 3.6
      env: *_coverage
      before_install: *_before_install
      install: *_install
      after_success:
        - codecov
  fast_finish: true
script:
- (eval "$SCRIPT")
notifications:
  email: false
